[0m23:55:00.805990 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264B958EBA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264BA9E3ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264BA9E3C50>]}


============================== 23:55:00.811610 | 193c67fb-d195-4544-9156-da69cb2ce4e5 ==============================
[0m23:55:00.811610 [info ] [MainThread]: Running with dbt=1.10.11
[0m23:55:00.812648 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt init', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'use_experimental_parser': 'False', 'printer_width': '80', 'indirect_selection': 'eager', 'log_path': 'logs', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'C:\\Users\\h.boulaayad\\.dbt'}
[0m23:55:00.844251 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\h.boulaayad\.dbt
[0m23:57:01.359206 [debug] [MainThread]: Starter project path: C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\include\starter_project
[0m23:57:01.399526 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:57:01.400521 [info ] [MainThread]: Setting up your profile.
[0m00:04:14.542188 [info ] [MainThread]: Profile dbt_project written to C:\Users\h.boulaayad\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:04:14.543810 [debug] [MainThread]: Command `dbt init` succeeded at 00:04:14.543646 after 553.90 seconds
[0m00:04:14.544174 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264CC9D3950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264BBB1C950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264CCA3D590>]}
[0m00:04:14.544536 [debug] [MainThread]: Flushing usage events
[0m00:04:15.056179 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:18:36.469779 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B53F0EBA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B5537BED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B5537BC50>]}


============================== 00:18:36.474916 | 8c623120-eafc-44c4-8c2a-f8ce93bb9ced ==============================
[0m00:18:36.474916 [info ] [MainThread]: Running with dbt=1.10.11
[0m00:18:36.475519 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'use_experimental_parser': 'False', 'printer_width': '80', 'indirect_selection': 'eager', 'log_path': 'logs', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'C:\\Users\\h.boulaayad\\.dbt'}
[0m00:18:36.475990 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\h.boulaayad\Documents\BachelorArbeit\ETL_COVID19\dbt_Project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:18:36.476974 [debug] [MainThread]: Command `dbt run` failed at 00:18:36.476868 after 0.15 seconds
[0m00:18:36.477272 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B55391A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B553F84D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B551E7570>]}
[0m00:18:36.477574 [debug] [MainThread]: Flushing usage events
[0m00:18:36.942333 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:21:24.145438 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE8803EBA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE8949BED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE8949BC50>]}


============================== 00:21:24.151056 | 0be030d1-8ad6-40cb-ac95-fbd69630bda4 ==============================
[0m00:21:24.151056 [info ] [MainThread]: Running with dbt=1.10.11
[0m00:21:24.151754 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\h.boulaayad\\.dbt', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'empty': 'False', 'printer_width': '80', 'log_path': 'logs', 'indirect_selection': 'eager', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m00:21:24.152180 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\h.boulaayad\Documents\BachelorArbeit\ETL_COVID19\DBT_PROJECT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:21:24.153378 [debug] [MainThread]: Command `dbt run` failed at 00:21:24.153270 after 0.16 seconds
[0m00:21:24.153667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE894B5A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE895184D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE89307570>]}
[0m00:21:24.153952 [debug] [MainThread]: Flushing usage events
[0m00:21:24.586220 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:32:05.542132 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A24BCEBA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A2602BED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A2602BC50>]}


============================== 00:32:05.547462 | 0f359be3-133c-4f98-bcbd-cd5784dc844d ==============================
[0m00:32:05.547462 [info ] [MainThread]: Running with dbt=1.10.11
[0m00:32:05.548360 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'empty': 'False', 'printer_width': '80', 'indirect_selection': 'eager', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\h.boulaayad\\.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'write_json': 'True'}
[0m00:32:05.548796 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\h.boulaayad\Documents\BachelorArbeit\ETL_COVID19\DBT_PROJECT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:32:05.550044 [debug] [MainThread]: Command `dbt run` failed at 00:32:05.549939 after 0.13 seconds
[0m00:32:05.550323 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A26041A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A260A84D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A25E93570>]}
[0m00:32:05.550603 [debug] [MainThread]: Flushing usage events
[0m00:32:06.058418 [debug] [MainThread]: An error was encountered while trying to flush usage events
